[package]
name = "frontend"
version = "0.2.0"
edition = "2021"

[dependencies]
leptos = { version = "0.6", features = ["csr"] }
leptos_router = { version = "0.6", features = ["csr"] }
console_error_panic_hook = "0.1"
console_log = "1"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
gloo-net = "0.5"
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["HtmlElement", "Node", "Window", "Document", "Element", "Event", "MouseEvent", "InputEvent", "FileList", "File", "Url", "IntersectionObserver", "IntersectionObserverEntry", "IntersectionObserverInit", "ScrollIntoViewOptions", "ScrollLogicalPosition", "ScrollBehavior"] }
chrono = { version = "0.4", features = ["serde", "wasmbind"] }

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
